### ISSUE TITLE
How is the usage of this project

### ISSUE THREAD

**Issue by SunnerLi** [sczhengyabin/Google-Image-Downloader#1]
I just download and install the corresponding dependency.
Next, I revise the content in the main.py and run.
But I just stuck without responses as below:

``` shell
sunner@sunner-All-Series:~/Save/Google-Image-Downloader/src$ python main.py 

Scraping From Google Image Search ...

Keywords:   orange
Number:     100
Face Only:  Yes
Safe Mode:  On
Query URL:  https://www.google.com/search?tbm=isch&q=orange&tbs=itp:face&safe=on

```

The status keeps for several minutes until I do key interruption.
However, no error description appeared.
Is there any problem about my operation?
My environment is ubuntu 14.04, Python 2.7.6.

**Comment by sczhengyabin** [comment]
Is your network has access to Google?
If not, perhaps you have to setup a proxy and modify the proxy parameter in main.py to get it work!
